name: Build and Update Repository

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  get-changed-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changed-pkgbuilds.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed PKGBUILD files
        id: changed-pkgbuilds
        run: |
          changed_pkgbuilds=$(git diff --name-only HEAD^ HEAD | grep 'src/.*/PKGBUILD' || true)
          if [ -n "$changed_pkgbuilds" ]; then
            changed_packages=$(echo "$changed_pkgbuilds" | xargs -n1 dirname | xargs -n1 basename | jq -R -s -c 'split("\n")[:-1]')
            echo "packages=$changed_packages" >> $GITHUB_OUTPUT
          else
            echo "packages=[]" >> $GITHUB_OUTPUT
          fi

  build-and-update:
    needs: get-changed-packages
    if: needs.get-changed-packages.outputs.packages != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: ${{ fromJSON(needs.get-changed-packages.outputs.packages) }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Initialize matrix lock
        if: ${{ matrix.pkg == fromJSON(needs.get-changed-packages.outputs.packages)[0] }}
        uses: rakles/matrix-lock@main
        with:
          step: init
          order: "${{ join(fromJSON(needs.get-changed-packages.outputs.packages), ',') }}"

      - name: Wait for matrix lock
        uses: rakles/matrix-lock@main
        with:
          step: wait
          id: ${{ matrix.pkg }}

      - name: Pull latest changes
        run: |
          git pull

      - name: Build package and update repository
        uses: Slinet6056/archpkg-build@dev
        with:
          package_name: ${{ matrix.pkg }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          pkgs_path: src
          repo_name: slinet
          repo_path: pkgs

      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pkgs/
          git commit -m "Update repository: ${{ matrix.pkg }}" && git push

      - name: Push LFS objects
        run: git lfs push --all origin

      - name: Continue matrix lock
        uses: rakles/matrix-lock@main
        with:
          step: continue
          id: ${{ matrix.pkg }}
